version: 0.2

phases:
  build:
    commands:
      - echo "Preparing production artifacts..."
      - mkdir html
      - cp index.html html/
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*.html'
  base-directory: 'html'
  discard-paths: no