version: 0.2

phases:
  build:
    commands:
      - echo "Preparing production artifacts..."
      - mkdir dist
      - cp index.html dist/
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: dist
  discard-paths: yes