version: 0.2

phases:
  build:
    commands:
      - echo "No compilation required for this static website."
      - echo "Current directory content:"
      - ls -la
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - index.html
    - README.md
    - '**/*'
  discard-paths: no